sudo: false
language: php
php:
  - '7.1'
  - '7.2'
  - nightly
before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
script:
  - chmod -R 777 tests/build
  - ./vendor/bin/phpunit --coverage-clover tests/build/clover.xml
after_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then php vendor/bin/php-coveralls -v; fi
  - composer security-checker
